import "./globals.css";

export const metadata = {
  title: "System Client",
  description: "Generated by Idriss",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
